// EDITA AQUÍ: cantidad de elementos, imágenes y frases de la galaxia.
// Los colores, las fuentes y el diseño del inicio están en styles.css.
export const SETTINGS = {
  particles: { arms: 42000, dust: 10000, stars: 6500 },
  introParticles: 130,
  flowerCount: 50,
  flowerOpacity: 0.65, // 0 = invisible; 1 = completamente opaca.
  phraseCount: 84, // Si supera la lista, las frases se repiten.
  phraseSize: 42,
  phraseFont: '52px "Great Vibes"',
  flowerImages: [
    "flor-1.png",
    "flor-2.png",
    "flor-3.png",
    "flor-4.png",
    "flor-5.png",
  ],
};

// Añade o cambia frases: una por línea, entre comillas y con coma al final.
export const PHRASES = [
  "Eres mi flor favorita",
  "Gracias por tanto cariño",
  "Contigo todo florece",
  "Me haces sonreír sin darte cuenta",
  "Te amo mucho, princesa",
  "Un universo para ti",
  "Me gusta verte sonreír",
  "Gracias por estar en mi vida",
  "Cada flor es un pensamiento bonito",
  "Mi lugar favorito es contigo",
  "Eres mi casualidad favorita",
  "Me encanta tu forma de ser",
  "Qué bonito coincidir contigo",
  "Hoy el morado te sonríe",
  "Eres mi persona especial",
  "Contigo los días son más bonitos",
  "Tu sonrisa ilumina mis días",
  "Mi amor por ti sigue creciendo",
  "Eres un pedacito de mi felicidad",
  "Me gusta todo de ti",
  "Te escogería una y mil veces",
  "Mi corazón sonríe contigo",
  "Tú haces especial lo sencillo",
  "Gracias por los momentos bonitos",
  "Eres una razón para sonreír",
  "Un abrazo para mi princesa",
  "Me encantas más de lo que imaginas",
  "Cada estrella guarda un te quiero",
  "Para ti, mi amor",
  "Que nunca te falten flores",
  "Si estás tú, estoy en casa",
  "Mi cielo empieza en tus ojos",
  "Eres mi sueño más bonito",
  "Te quiero cerquita de mi vida",
  "Tú y yo, en todas mis vidas",
  "Tu abrazo es mi lugar seguro",
  "Me enamoro de ti cada día",
  "Todo es más bonito a tu lado",
  "Eres la magia de mis días",
  "Quiero mil atardeceres contigo",
  "Mi universo lleva tu nombre",
  "Tus besos son mi poesía",
  "Te llevo en cada latido",
  "Eres mi hoy y mi ojalá siempre",
  "Mi corazón siempre te elige",
  "Donde estés tú, quiero estar",
  "Qué suerte la mía encontrarte",
  "Tienes mi sonrisa favorita",
  "Quiero cuidarte el corazón",
  "A tu lado florece mi vida",
  "Mi deseo siempre eres tú",
  "Tu risa me ilumina el alma",
  "Amarte es mi aventura favorita",
  "Te pienso en cada estrella",
  "Eres mi abrazo pendiente",
  "Siempre hay un te amo para ti",
  "Mi amor crece contigo",
  "Me quedaría en tus abrazos",
  "Eres mi más bonita historia",
  "Todos mis caminos van hacia ti",
  "Un beso tuyo y todo está bien",
  "Te elijo incluso en mis sueños",
  "Tú haces latir mi universo",
  "Mi amor por ti no tiene prisa",
  "Mi lugar en el mundo eres tú",
  "Contigo, hasta las estrellas",
  "Eres mi paz y mi alegría",
  "Quiero escribir mi vida contigo",
  "En tus ojos encontré mi cielo",
  "Eres la flor de todos mis días",
];
